server:
  port: 9016
#################################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
#################################################
spring:
  application:
    name: eureka-consumer-dept-ribbonAddHystrix
