server:
  port: 9003
##############################################################
mybatis:
  type-aliases-package: com.faraway.common.entity               # 所有Entity别名类所在包
  mapper-locations: classpath:mapper/*.xml                      # mapper映射文件
##############################################################
spring:
  application:
    name: eureka-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
##############################################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
